[package]
name = "markdown-parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = {version = "1.0.163", features = ["derive"]}
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.86"

[dev-dependencies]
wasm-bindgen-test = "0.3.36"